spring:
  flyway:
    enabled: false
    baseline-on-migrate: true
    url: jdbc:mysql://${DB_WRITER_HOST}:${DB_WRITER_PORT}/aptpan?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    user: ${DB_WRITER_USERNAME}
    password: ${DB_WRITER_PASSWORD}
    locations: classpath:db/migration
