server:
  port: 8080
spring:
  profiles:
    group:
      default: application, domain, infrastructure, support-migration
      test: application-test, domain-test, infrastructure-test, support-migration-test
      prod: application-prod, domain-prod, infrastructure-prod, support-migration-prod
  mvc:
    static-path-pattern: /test/**
  main:
    banner-mode: off
logging:
  level:
    org.springframework.kafka.*: OFF
    org.springframework.kafka.listener.[KafkaMessageListenerContainer$ListenerConsumer]: OFF
    org.apache.kafka.*: OFF
    kafka.*: OFF
    org.apache.zookeeper.*: OFF
