spring:
  datasource:
    writer:
      hikari:
        jdbc-url: jdbc:mysql://${DB_WRITER_HOST}:${DB_WRITER_PORT}/aptpan?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
        username: ${DB_WRITER_USERNAME}
        password: ${DB_WRITER_PASSWORD}
        pool-name: 'read-write-pool'
        driver-class-name: com.mysql.cj.jdbc.Driver
    reader:
      hikari:
        jdbc-url: jdbc:mysql://${DB_WRITER_HOST}:${DB_WRITER_PORT}/aptpan?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
        username: ${DB_WRITER_USERNAME}
        password: ${DB_WRITER_PASSWORD}
        pool-name: 'read-pool'
        driver-class-name: com.mysql.cj.jdbc.Driver
        read-only: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: false
    baseline-on-migrate: true
    url: jdbc:mysql://${DB_WRITER_HOST}:${DB_WRITER_PORT}/aptpan?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    user: ${DB_WRITER_USERNAME}
    password: ${DB_WRITER_PASSWORD}
    locations: classpath:db/migration
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
